### ISSUE TITLE
Error in dependencies wrt webpack

### ISSUE THREAD

**Issue by gregertw** [Seedstars/django-react-redux-base#49] opened 2016-12-23 19:17 UTC
I get the following errors on dependencies after webpack was upgraded to webpack 2.2.0rc1:
npm WARN bootstrap-loader@2.0.0-beta.16 requires a peer of webpack@^2.1.0-beta but none was installed.
npm WARN extract-text-webpack-plugin@2.0.0-beta.4 requires a peer of webpack@^2.1.0-beta.19 but none was installed.
npm WARN html-webpack-plugin@2.24.1 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
npm WARN sass-loader@4.1.0 requires a peer of webpack@^1.12.6 || ^2.1.0-beta but none was installed.

**Comment by MengJueM** [comment] 2016-12-24 00:50
the webpack version in package is 2.2.1-rc1，i think this issue is caused by npm, i resolved by change 2.2.1-rc1 to 2.1.0-beta.

**Comment by lfrodrigues** [comment] 2016-12-24 18:02
This is due to the RC version of webpack we are using. As soon as webpack 2.2 is released we will update and it will be solved.

**Closed by lfrodrigues** 2016-12-24 18:02 UTC
