### ISSUE TITLE
Series of errors on clean install

### ISSUE THREAD

**Issue by gregertw** [Seedstars/django-react-redux-base#45] opened 2016-12-17 08:31 UTC
Thanks for a great project! I would like to offer some comments/experiences when starting from scratch.
I started from scratch on a mac and installed everything according to instructions. I got a number of issues:

**--edited issues (added numbering)--**
1. References in README are not updated to djangoreactreduxjwtbase_* (add jwt)
2. The scripts submodule has already been added in the repository, so README is not correct in the need to add culture-scripts
3. I had an older version of npm that confused me for a while. It would be useful to document minimum npm version
4. When running frontend tests, I get an error Failed at the django-react-redux-jwt-base@1.0.0 coverage script 'istanbul cover node_modules/mocha/bin/_mocha -- --require tests/require --recursive --compilers js:babel-core/register --colors --reporter dot tests/js/' 
See [npm-debug.log.txt](https://github.com/Seedstars/django-react-redux-base/files/658735/npm-debug.log.txt)
5. When starting the containers (using Docker for Mac), everything seems to start ok, but when accessing http://localhost:8000/, I get a File not found and several modules (font-awesome etc) not found in the console log. Then I need to wait 55 seconds(!), refresh my browser and then it works
6. Finally, when running the backend tests, I get several 'The ``fake-factory`` package is now called ``Faker`` errors.

```
Starting djangoreactreduxjwtbase_postgres_1
Starting djangoreactreduxjwtbase_backend_1
Starting djangoreactreduxjwtbase_nginx_1
Starting djangoreactreduxjwtbase_frontend_1
Attaching to djangoreactreduxjwtbase_postgres_1, djangoreactreduxjwtbase_backend_1, djangoreactreduxjwtbase_frontend_1, djangoreactreduxjwtbase_nginx_1
postgres_1  | LOG:  database system was shut down at 2016-12-17 08:25:22 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
backend_1   | Operations to perform:
backend_1   |   Synchronize unmigrated apps: staticfiles, rest_framework, accounts, django_extensions, base
postgres_1  | LOG:  database system is ready to accept connections
backend_1   |   Apply all migrations: knox, auth, contenttypes
backend_1   | Synchronizing apps without migrations:
backend_1   |   Creating tables...
postgres_1  | LOG:  autovacuum launcher started
backend_1   |     Running deferred SQL...
backend_1   |   Installing custom SQL...
backend_1   | Running migrations:
backend_1   |   No migrations to apply.
frontend_1  | yarn install v0.17.10
frontend_1  | [1/4] Resolving packages...
backend_1   | Installed 1 object(s) from 1 fixture(s)
frontend_1  | success Already up-to-date.
frontend_1  | Done in 0.66s.
frontend_1  | 
frontend_1  | > django-react-redux-jwt-base@1.0.0 dev /django
frontend_1  | > webpack --progress --display-error-details --config webpack/common.config.js --watch
frontend_1  | 
backend_1   | Performing system checks...
backend_1   | 
backend_1   | System check identified no issues (0 silenced).
backend_1   | December 17, 2016 - 08:25:58
backend_1   | Django version 1.8.15, using settings 'djangoreactredux.settings.dev'
backend_1   | Starting development server at http://0.0.0.0:8000/
backend_1   | Quit the server with CONTROL-C.
frontend_1  | clean-webpack-plugin: /django/src/static_dist has been removed.
backend_1   | [17/Dec/2016 08:26:06] "GET / HTTP/1.0" 500 83907
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:26:06 +0000] "GET / HTTP/1.1" 500 84015 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:26:07 +0000] "GET /favicon.ico HTTP/1.1" 500 83668 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
backend_1   | [17/Dec/2016 08:26:07] "GET /favicon.ico HTTP/1.0" 500 83568
backend_1   | [17/Dec/2016 08:26:13] "GET / HTTP/1.0" 500 83293
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:26:13 +0000] "GET / HTTP/1.1" 500 83393 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
backend_1   | [17/Dec/2016 08:26:13] "GET /favicon.ico HTTP/1.0" 500 83568
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:26:13 +0000] "GET /favicon.ico HTTP/1.1" 500 83668 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
backend_1   | [17/Dec/2016 08:26:20] "GET / HTTP/1.0" 500 83293
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:26:20 +0000] "GET / HTTP/1.1" 500 83400 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
backend_1   | [17/Dec/2016 08:26:21] "GET /favicon.ico HTTP/1.0" 500 83568
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:26:21 +0000] "GET /favicon.ico HTTP/1.1" 500 83668 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
 11% building modules 15/53 modules 38 active ...de_modules/redux/lib/utils/warning.jsnode_modules/nan
frontend_1  | resolve failed:  { Error: Cannot find module 'font-awesome'
frontend_1  |     at Function.Module._resolveFilename (module.js:469:15)
frontend_1  |     at Function.requireRelative.resolve (/django/node_modules/require-relative/index.js:30:17)
frontend_1  |     at resolve (/django/node_modules/modify-babel-preset/lib/serialize.js:26:26)
frontend_1  |     at findAndRemove (/django/node_modules/modify-babel-preset/lib/serialize.js:83:11)
frontend_1  |     at /django/node_modules/modify-babel-preset/lib/serialize.js:126:13
frontend_1  |     at Array.map (native)
frontend_1  |     at loadPreset (/django/node_modules/modify-babel-preset/lib/serialize.js:118:29)
frontend_1  |     at module.exports (/django/node_modules/modify-babel-preset/index.js:95:19)
frontend_1  |     at Object.<anonymous> (/django/node_modules/babel-preset-es2015-loose/index.js:5:18)
frontend_1  |     at Module._compile (module.js:570:32)
frontend_1  |     at Object.Module._extensions..js (module.js:579:10)
frontend_1  |     at Module.load (module.js:487:32)
frontend_1  |     at tryModuleLoad (module.js:446:12)
frontend_1  |     at Function.Module._load (module.js:438:3)
frontend_1  |     at Module.require (module.js:497:17)
frontend_1  |     at require (internal/module.js:20:19)
frontend_1  |     at /django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
frontend_1  |     at Array.map (native)
frontend_1  |     at OptionManager.resolvePresets (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
frontend_1  |     at OptionManager.mergePresets (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
frontend_1  |     at OptionManager.mergeOptions (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
frontend_1  |     at OptionManager.init (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
frontend_1  |     at File.initOptions (/django/node_modules/babel-core/lib/transformation/file/index.js:216:65)
frontend_1  |     at new File (/django/node_modules/babel-core/lib/transformation/file/index.js:139:24)
frontend_1  |     at Pipeline.transform (/django/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
frontend_1  |     at transpile (/django/node_modules/babel-loader/lib/index.js:41:20)
frontend_1  |     at Object.module.exports (/django/node_modules/babel-loader/lib/index.js:138:12)
frontend_1  |     at LOADER_EXECUTION (/django/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
frontend_1  |     at runSyncOrAsync (/django/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
frontend_1  |     at iterateNormalLoaders (/django/node_modules/loader-runner/lib/LoaderRunner.js:224:2) code: 'MODULE_NOT_FOUND' } font-awesome
frontend_1  | resolve failed:  { Error: Cannot find module 'eslint-module-utils'
frontend_1  |     at Function.Module._resolveFilename (module.js:469:15)
frontend_1  |     at Function.requireRelative.resolve (/django/node_modules/require-relative/index.js:30:17)
frontend_1  |     at resolve (/django/node_modules/modify-babel-preset/lib/serialize.js:26:26)
frontend_1  |     at findAndRemove (/django/node_modules/modify-babel-preset/lib/serialize.js:83:11)
frontend_1  |     at /django/node_modules/modify-babel-preset/lib/serialize.js:126:13
frontend_1  |     at Array.map (native)
frontend_1  |     at loadPreset (/django/node_modules/modify-babel-preset/lib/serialize.js:118:29)
frontend_1  |     at module.exports (/django/node_modules/modify-babel-preset/index.js:95:19)
frontend_1  |     at Object.<anonymous> (/django/node_modules/babel-preset-es2015-loose/index.js:5:18)
frontend_1  |     at Module._compile (module.js:570:32)
frontend_1  |     at Object.Module._extensions..js (module.js:579:10)
frontend_1  |     at Module.load (module.js:487:32)
frontend_1  |     at tryModuleLoad (module.js:446:12)
frontend_1  |     at Function.Module._load (module.js:438:3)
frontend_1  |     at Module.require (module.js:497:17)
frontend_1  |     at require (internal/module.js:20:19)
frontend_1  |     at /django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
frontend_1  |     at Array.map (native)
frontend_1  |     at OptionManager.resolvePresets (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
frontend_1  |     at OptionManager.mergePresets (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
frontend_1  |     at OptionManager.mergeOptions (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
frontend_1  |     at OptionManager.init (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
frontend_1  |     at File.initOptions (/django/node_modules/babel-core/lib/transformation/file/index.js:216:65)
frontend_1  |     at new File (/django/node_modules/babel-core/lib/transformation/file/index.js:139:24)
frontend_1  |     at Pipeline.transform (/django/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
frontend_1  |     at transpile (/django/node_modules/babel-loader/lib/index.js:41:20)
frontend_1  |     at Object.module.exports (/django/node_modules/babel-loader/lib/index.js:138:12)
frontend_1  |     at LOADER_EXECUTION (/django/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
frontend_1  |     at runSyncOrAsync (/django/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
frontend_1  |     at iterateNormalLoaders (/django/node_modules/loader-runner/lib/LoaderRunner.js:224:2) code: 'MODULE_NOT_FOUND' } eslint-module-utils
frontend_1  | resolve failed:  { Error: Cannot find module 'caniuse-db'
frontend_1  |     at Function.Module._resolveFilename (module.js:469:15)
frontend_1  |     at Function.requireRelative.resolve (/django/node_modules/require-relative/index.js:30:17)
frontend_1  |     at resolve (/django/node_modules/modify-babel-preset/lib/serialize.js:26:26)
frontend_1  |     at findAndRemove (/django/node_modules/modify-babel-preset/lib/serialize.js:83:11)
frontend_1  |     at /django/node_modules/modify-babel-preset/lib/serialize.js:126:13
frontend_1  |     at Array.map (native)
frontend_1  |     at loadPreset (/django/node_modules/modify-babel-preset/lib/serialize.js:118:29)
frontend_1  |     at module.exports (/django/node_modules/modify-babel-preset/index.js:95:19)
frontend_1  |     at Object.<anonymous> (/django/node_modules/babel-preset-es2015-loose/index.js:5:18)
frontend_1  |     at Module._compile (module.js:570:32)
frontend_1  |     at Object.Module._extensions..js (module.js:579:10)
frontend_1  |     at Module.load (module.js:487:32)
frontend_1  |     at tryModuleLoad (module.js:446:12)
frontend_1  |     at Function.Module._load (module.js:438:3)
frontend_1  |     at Module.require (module.js:497:17)
frontend_1  |     at require (internal/module.js:20:19)
frontend_1  |     at /django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
frontend_1  |     at Array.map (native)
frontend_1  |     at OptionManager.resolvePresets (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
frontend_1  |     at OptionManager.mergePresets (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
frontend_1  |     at OptionManager.mergeOptions (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
frontend_1  |     at OptionManager.init (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
frontend_1  |     at File.initOptions (/django/node_modules/babel-core/lib/transformation/file/index.js:216:65)
frontend_1  |     at new File (/django/node_modules/babel-core/lib/transformation/file/index.js:139:24)
frontend_1  |     at Pipeline.transform (/django/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
frontend_1  |     at transpile (/django/node_modules/babel-loader/lib/index.js:41:20)
frontend_1  |     at Object.module.exports (/django/node_modules/babel-loader/lib/index.js:138:12)
frontend_1  |     at LOADER_EXECUTION (/django/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
frontend_1  |     at runSyncOrAsync (/django/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
frontend_1  |     at iterateNormalLoaders (/django/node_modules/loader-runner/lib/LoaderRunner.js:224:2) code: 'MODULE_NOT_FOUND' } caniuse-db
frontend_1  | resolve failed:  { Error: Cannot find module 'babel-runtime'
frontend_1  |     at Function.Module._resolveFilename (module.js:469:15)
frontend_1  |     at Function.requireRelative.resolve (/django/node_modules/require-relative/index.js:30:17)
frontend_1  |     at resolve (/django/node_modules/modify-babel-preset/lib/serialize.js:26:26)
frontend_1  |     at findAndRemove (/django/node_modules/modify-babel-preset/lib/serialize.js:83:11)
frontend_1  |     at /django/node_modules/modify-babel-preset/lib/serialize.js:126:13
frontend_1  |     at Array.map (native)
frontend_1  |     at loadPreset (/django/node_modules/modify-babel-preset/lib/serialize.js:118:29)
frontend_1  |     at module.exports (/django/node_modules/modify-babel-preset/index.js:95:19)
frontend_1  |     at Object.<anonymous> (/django/node_modules/babel-preset-es2015-loose/index.js:5:18)
frontend_1  |     at Module._compile (module.js:570:32)
frontend_1  |     at Object.Module._extensions..js (module.js:579:10)
frontend_1  |     at Module.load (module.js:487:32)
frontend_1  |     at tryModuleLoad (module.js:446:12)
frontend_1  |     at Function.Module._load (module.js:438:3)
frontend_1  |     at Module.require (module.js:497:17)
frontend_1  |     at require (internal/module.js:20:19)
frontend_1  |     at /django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
frontend_1  |     at Array.map (native)
frontend_1  |     at OptionManager.resolvePresets (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
frontend_1  |     at OptionManager.mergePresets (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
frontend_1  |     at OptionManager.mergeOptions (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
frontend_1  |     at OptionManager.init (/django/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
frontend_1  |     at File.initOptions (/django/node_modules/babel-core/lib/transformation/file/index.js:216:65)
frontend_1  |     at new File (/django/node_modules/babel-core/lib/transformation/file/index.js:139:24)
frontend_1  |     at Pipeline.transform (/django/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
frontend_1  |     at transpile (/django/node_modules/babel-loader/lib/index.js:41:20)
frontend_1  |     at Object.module.exports (/django/node_modules/babel-loader/lib/index.js:138:12)
frontend_1  |     at LOADER_EXECUTION (/django/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
frontend_1  |     at runSyncOrAsync (/django/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
frontend_1  |     at iterateNormalLoaders (/django/node_modules/loader-runner/lib/LoaderRunner.js:224:2) code: 'MODULE_NOT_FOUND' } babel-runtime
frontend_1  | Version: webpack 2.1.0-beta.15
frontend_1  | Time: 55231ms
frontend_1  |                                                   Asset       Size  Chunks             Chunk Names
frontend_1  |                 /fonts/glyphicons-halflings-regular.ttf    45.4 kB          [emitted]  
frontend_1  |                 /fonts/glyphicons-halflings-regular.eot    20.1 kB          [emitted]  
frontend_1  | /images/react-logo.png?bf6e7aa4366ba93442e42038897d683d    35.1 kB          [emitted]  
frontend_1  | /images/redux-logo.png?59c467536111a981d904a050d335c2be     218 kB          [emitted]  
frontend_1  |                /fonts/glyphicons-halflings-regular.woff    23.4 kB          [emitted]  
frontend_1  |                         /fonts/fontawesome-webfont.woff      98 kB          [emitted]  
frontend_1  |               /fonts/glyphicons-halflings-regular.woff2      18 kB          [emitted]  
frontend_1  |                        /fonts/fontawesome-webfont.woff2    77.2 kB          [emitted]  
frontend_1  |                          /fonts/fontawesome-webfont.eot     166 kB          [emitted]  
frontend_1  |                          /fonts/fontawesome-webfont.ttf     166 kB          [emitted]  
frontend_1  |                 /fonts/glyphicons-halflings-regular.svg     109 kB          [emitted]  
frontend_1  |                          /fonts/fontawesome-webfont.svg     444 kB          [emitted]  
frontend_1  |                          vendor.3962ffc3e7f549f8c9e3.js    1.74 MB       0  [emitted]  vendor
frontend_1  |                             app.3962ffc3e7f549f8c9e3.js     656 kB       1  [emitted]  app
frontend_1  |                      vendor.3962ffc3e7f549f8c9e3.js.map    2.19 MB       0  [emitted]  vendor
frontend_1  |                         app.3962ffc3e7f549f8c9e3.js.map     822 kB       1  [emitted]  app
frontend_1  |                                              index.html  441 bytes          [emitted]  
frontend_1  | [1078] multi vendor 172 bytes {0} [built]
frontend_1  |     + 1086 hidden modules
frontend_1  | Child html-webpack-plugin for "index.html":
frontend_1  |         + 4 hidden modules
backend_1   | [17/Dec/2016 08:28:03] "GET / HTTP/1.0" 200 441
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:28:03 +0000] "GET / HTTP/1.1" 200 453 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:28:03 +0000] "GET /static/app.3962ffc3e7f549f8c9e3.js?3962ffc3e7f549f8c9e3 HTTP/1.1" 200 656421 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
backend_1   | [17/Dec/2016 08:28:03] "GET /static/app.3962ffc3e7f549f8c9e3.js?3962ffc3e7f549f8c9e3 HTTP/1.0" 200 656421
backend_1   | [17/Dec/2016 08:28:03] "GET /static/vendor.3962ffc3e7f549f8c9e3.js?3962ffc3e7f549f8c9e3 HTTP/1.0" 200 1736691
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:28:03 +0000] "GET /static/vendor.3962ffc3e7f549f8c9e3.js?3962ffc3e7f549f8c9e3 HTTP/1.1" 200 1736691 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:28:03 +0000] "GET /static/fonts/fontawesome-webfont.woff2 HTTP/1.1" 200 77160 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
backend_1   | [17/Dec/2016 08:28:03] "GET /static/fonts/fontawesome-webfont.woff2 HTTP/1.0" 200 77160
backend_1   | [17/Dec/2016 08:28:03] "GET /static/images/react-logo.png?bf6e7aa4366ba93442e42038897d683d HTTP/1.0" 200 35133
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:28:03 +0000] "GET /static/images/react-logo.png?bf6e7aa4366ba93442e42038897d683d HTTP/1.1" 200 35133 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:28:03 +0000] "GET /static/images/redux-logo.png?59c467536111a981d904a050d335c2be HTTP/1.1" 200 217989 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
backend_1   | [17/Dec/2016 08:28:03] "GET /static/images/redux-logo.png?59c467536111a981d904a050d335c2be HTTP/1.0" 200 217989
backend_1   | [17/Dec/2016 08:28:04] "GET /favicon.ico HTTP/1.0" 200 441
nginx_1     | 172.18.0.1 - - [17/Dec/2016:08:28:04 +0000] "GET /favicon.ico HTTP/1.1" 200 453 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36" "-"
```

**Comment by fgarci03** [comment] 2016-12-17 14:56
Hi @gregertw thanks for the input!

Here are my preliminary findings:

1. The project is now called django-react-redux-base (without the jwt). I found references to jwt still, and will remove them
2. I assume you are talking about the reference:
> Remember that when you copy this repository for a new project you need to add the scripts external module...

If so, this reference is for when you copy the code to start a new project, not when you clone or fork the repository. Did I understand wrong?

3. Aaaaarg! I forgot to add that since it's all (mostly) handled by docker :slightly_smiling_face: 
4. looking into it
5. looking into it
6. The issue is with the version of factory-boy (currently at 2.7.0 in the py-requirements). With 2.8.1 everything seems to be working correctly. Will update it :+1:

**Comment by gregertw** [comment] 2016-12-17 18:31
Hi @fgarci03, thanks for picking it up so fast. Glad to help.
To 1, yes, it was a bit confusing. I actually thought jwt was the correct name.
To 2, I'm still not sure I understand that sentence although I now understand that I misunderstood :) I thought it was an old comment, not referring to using cp. However, it would quite useful to extend that paragraph for a new person to get some information about how to start a new project. 
Happy to retest if you have something you want me to validate.

**Comment by fgarci03** [comment] 2016-12-18 15:48
@gregertw Issues 1, 2, 3 & 6 are addressed in this commit. Still looking into 4 & 5 (they seem to be the exact same problem actually).

This seems to happen even on older commits, which is odd, as it wasn't happening last week. If you have any insights on what the problem may be, please share :slightly_smiling_face: 
I will update as soon as I find something.

Thanks!

**Closed** 2016-12-21 10:51 UTC
Labels: bug
