### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by sauravskumar** [Seedstars/django-react-redux-base#58] opened 2017-02-12 19:10 UTC
Doing a docker build on the following repo as defined in the readme file is giving and error

```
docker-compose build
postgres uses an image, skipping
Building backend
Step 1/8 : FROM python:3.4.3
 ---> 2b07576f6f81
Step 2/8 : MAINTAINER Filipe Garcia <filipe.garcia@seedstarslabs.com>
 ---> Using cache
 ---> fb8c1164eb76
Step 3/8 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> cac86ae2aca7
Step 4/8 : COPY ./docker/django/django-entrypoint.sh /
 ---> Using cache
 ---> e92f5fac5331
Step 5/8 : COPY ./py-requirements /django/py-requirements
 ---> Using cache
 ---> 141951255c71
Step 6/8 : WORKDIR /django
 ---> Using cache
 ---> df57582f5732
Step 7/8 : RUN pip install pip==9.0.1
 ---> Running in eb127faba904
Collecting pip==9.0.1
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', gaierror(-2, 'Name or service not known'))': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', gaierror(-2, 'Name or service not known'))': /simple/pip/

```

Can you please look into the readme file and update it accordingly

**Comment by fgarci03** [comment] 2017-02-14 15:02
Hi, @sauravskumar 

I haven't been able to reproduce this error, are you still having issues?
Can you run the pip install command without docker (python 3.4.3) and see if it works?

Could this have anything to do with [this](http://stackoverflow.com/questions/30276447/use-pip-intall-virtualenvprotocolerrorconnection-aborted-gaierror-3-tem)?

**Comment by fgarci03** [comment] 2017-06-01 10:44
Closing due to innactivity

**Closed by fgarci03** 2017-06-01 10:44 UTC
